# Generated by Django 6.1 on 2026-08-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
