# Generated by Django 5.2.17 on 2026-09-14 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_ai_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
