# Generated by Django 5.2.17 on 2026-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_description_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='events/thumbnails/%Y/%m/%d/'),
        ),
    ]
