# Generated by Django 5.2.17 on 2026-09-23 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventphoto_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_all_photos_accessible', models.BooleanField(default=False, help_text='If True, guests can directly see and download all photos without selfie search')),
                ('password', models.CharField(blank=True, help_text='Optional password to protect this link', max_length=128, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date and time', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
