# Generated by Django 5.2.17 on 2026-09-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventsharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Person', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='events/people/%Y/%m/')),
                ('face_count', models.IntegerField(default=0, help_text='Number of face instances detected for this person')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='events.event')),
                ('photos', models.ManyToManyField(blank=True, related_name='people', to='events.eventphoto')),
            ],
            options={
                'ordering': ['-face_count', 'id'],
            },
        ),
    ]
