# Generated by Django 5.2.17 on 2026-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='file_size',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='original_filename',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
