# Generated by Django 5.2.17 on 2026-09-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventphoto_file_hash_eventphoto_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='eventphoto',
            index=models.Index(fields=['event', 'processing_status'], name='events_even_event_i_481796_idx'),
        ),
    ]
