# Generated by Django 5.2.17 on 2026-09-28 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventphoto_error_message_eventphoto_retry_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('total_files', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('completed_chunks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoUploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('file_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='events.photouploadsession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'chunk_index'], name='events_phot_session_082d05_idx')],
                'unique_together': {('session', 'chunk_index')},
            },
        ),
    ]
